import psycopg2

def fix_defaults():
    conn = psycopg2.connect(
        dbname="tpv_test_db",
        user="admin",
        password="admin_password",
        host="localhost",
        port="5432"
    )
    conn.autocommit = True
    cursor = conn.cursor()
    
    # Obtener todas las columnas 'id'
    cursor.execute("""
        SELECT table_name, data_type 
        FROM information_schema.columns 
        WHERE column_name = 'id' AND table_schema = 'public';
    """)
    rows = cursor.fetchall()
    
    for table_name, data_type in rows:
        try:
            if data_type == 'uuid':
                sql = f'ALTER TABLE "{table_name}" ALTER COLUMN id SET DEFAULT gen_random_uuid();'
                cursor.execute(sql)
                print(f"Set gen_random_uuid for {table_name}")
            elif data_type in ('integer', 'bigint', 'numeric'):
                sql = f'ALTER TABLE "{table_name}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;'
                cursor.execute(sql)
                print(f"Set IDENTITY for {table_name}")
        except Exception as e:
            print(f"Error on {table_name}: {e}")
            
    # Obtener todas las columnas 'created_at'
    cursor.execute("""
        SELECT table_name 
        FROM information_schema.columns 
        WHERE column_name = 'created_at' AND table_schema = 'public';
    """)
    rows = cursor.fetchall()
    
    for (table_name,) in rows:
        try:
            sql = f'ALTER TABLE "{table_name}" ALTER COLUMN created_at SET DEFAULT now();'
            cursor.execute(sql)
            print(f"Set DEFAULT now() for {table_name}.created_at")
        except Exception as e:
            print(f"Error on {table_name}: {e}")
            
    # Also reload postgrest
    cursor.execute("NOTIFY pgrst, 'reload schema';")
    print("Defaults applied and Postgrest reloaded.")

if __name__ == '__main__':
    fix_defaults()
