--
-- PostgreSQL database dump (CI + Docker init local en BD nueva)
--

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agenda_bloqueos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_bloqueos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    fecha date,
    hora_inicio text,
    hora_fin text,
    titulo text,
    empleado_afectado text,
    bloquea_agenda boolean
);


--
-- Name: agenda_bloqueos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agenda_bloqueos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agenda_bloqueos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: citas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.citas (
    created_at timestamp with time zone DEFAULT now(),
    fecha_hora timestamp without time zone,
    servicio text,
    id bigint NOT NULL,
    mascotas_id uuid,
    duracion_minutos bigint,
    observaciones text
);


--
-- Name: citas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.citas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.citas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nombre_dueno text,
    telefono text,
    email text,
    direccion text,
    created_at timestamp with time zone DEFAULT now(),
    cif text,
    fecha_nacimiento text,
    puntos integer,
    rgpd_consent boolean,
    metodo_contacto text,
    nombre_dueno_2 text,
    telefono_2 text,
    servicio_domicilio boolean,
    auth_user_id uuid
);


--
-- Name: compras; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.compras (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    tipo text,
    total numeric,
    estado text,
    fecha_vencimiento date,
    proveedor_id uuid,
    productos jsonb,
    descuento_pp numeric,
    metodo_pago text,
    pagado numeric,
    pendiente numeric,
    fecha_factura date
);


--
-- Name: compras_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.compras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion (
    id integer NOT NULL,
    nombre_tienda text NOT NULL,
    envio_gratis_a_partir_de numeric NOT NULL,
    coste_envio_cercania numeric NOT NULL,
    coste_envio_lejos numeric NOT NULL,
    descuento_primera_compra_web_porcentaje numeric NOT NULL,
    descuento_cajas_completas_porcentaje numeric NOT NULL,
    euros_para_un_punto numeric NOT NULL,
    valor_punto_euros numeric NOT NULL,
    limite_descuento_puntos_porcentaje numeric NOT NULL,
    descuento_retorno_tienda_porcentaje numeric NOT NULL,
    dias_maximos_retorno_tienda integer NOT NULL,
    actualizado_en timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: configuracion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.configuracion_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: configuracion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.configuracion_id_seq OWNED BY public.configuracion.id;


--
-- Name: configuracion_negocio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion_negocio (
    id integer NOT NULL,
    nombre_tienda character varying(255),
    envio_gratis_a_partir_de numeric,
    coste_envio_cercania numeric,
    coste_envio_lejos numeric,
    euros_para_un_punto numeric,
    valor_punto_euros numeric,
    limite_descuento_puntos_porcentaje numeric,
    descuento_primera_compra_web_porcentaje numeric,
    descuento_cajas_completas_porcentaje numeric,
    descuento_retorno_tienda_porcentaje numeric,
    dias_maximos_retorno_tienda integer,
    actualizado_en timestamp with time zone
);


--
-- Name: configuracion_negocio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.configuracion_negocio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configuracion_negocio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: control_caja; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.control_caja (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    fondo_inicial numeric,
    estado text,
    total_contado numeric,
    descuadre numeric,
    resumen_pagos jsonb
);


--
-- Name: control_caja_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.control_caja ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.control_caja_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuentas_bancarias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cuentas_bancarias (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    nombre_banco text,
    titular text,
    iban text,
    saldo_actual numeric
);


--
-- Name: cuentas_bancarias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cuentas_bancarias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuentas_bancarias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: encargos_clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.encargos_clientes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    nombre_cliente text,
    telefono text,
    detalle_pedido text,
    notas text,
    estado text,
    origen text,
    recibido_por text
);


--
-- Name: encargos_clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.encargos_clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.encargos_clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos_asistentes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos_asistentes (
    id bigint NOT NULL,
    evento_id bigint,
    cliente_id uuid,
    pagado boolean
);


--
-- Name: eventos_asistentes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.eventos_asistentes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_asistentes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos_ferias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos_ferias (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    titulo text,
    fecha_inicio date,
    fecha_fin date,
    lugar text,
    presupuesto numeric,
    coste_real numeric,
    logistica_stands text,
    enlaces_planos text,
    estado text
);


--
-- Name: eventos_ferias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.eventos_ferias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_ferias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos_ferias_tareas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos_ferias_tareas (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    feria_id bigint,
    tarea text,
    responsable text,
    fecha_limite date,
    estado text
);


--
-- Name: eventos_ferias_tareas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.eventos_ferias_tareas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_ferias_tareas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos_talleres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos_talleres (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    titulo text,
    fecha date,
    hora text,
    plazas_totales integer,
    precio numeric,
    descripcion text
);


--
-- Name: eventos_talleres_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.eventos_talleres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_talleres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facturas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facturas (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    numero_factura integer,
    fecha_emision timestamp with time zone,
    cliente_id uuid,
    total_neto numeric,
    total_igic numeric,
    total_final numeric,
    hash_anterior text,
    hash_actual text,
    created_at timestamp with time zone DEFAULT now(),
    forma_pago text,
    fecha_vencimiento date,
    productos jsonb,
    descuento_global numeric,
    qr_verifactu text,
    estado_hacienda text
);


--
-- Name: gastos_recurrentes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gastos_recurrentes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    concepto text,
    categoria text,
    importe_estimado numeric,
    dia_cargo integer,
    frecuencia text,
    activo boolean
);


--
-- Name: gastos_recurrentes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gastos_recurrentes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gastos_recurrentes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marketing_objetivos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketing_objetivos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    titulo text,
    kpi_medidor text,
    meta_cuantitativa numeric,
    valor_actual numeric,
    fecha_inicio date,
    fecha_fin date,
    estado text,
    notas text
);


--
-- Name: marketing_objetivos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marketing_objetivos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marketing_objetivos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marketing_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketing_plan (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    fecha_planificada date,
    canal text,
    tema text,
    estado text,
    contenido_detallado text,
    presupuesto numeric,
    gasto_real numeric,
    tipo_campana text,
    canal_categoria text,
    objetivo_id bigint
);


--
-- Name: marketing_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marketing_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marketing_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mascotas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mascotas (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cliente_id uuid,
    nombre text,
    especie text,
    raza text,
    observaciones text,
    fecha_nacimiento text,
    historial_trabajos jsonb,
    peso text,
    sexo text
);


--
-- Name: movimientos_caja; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimientos_caja (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    id_caja bigint,
    tipo text,
    cantidad numeric,
    motivo text
);


--
-- Name: movimientos_caja_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movimientos_caja ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_caja_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notas_internas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notas_internas (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    autor text,
    destinatario text,
    asunto text,
    contenido text,
    urgencia text,
    estado text
);


--
-- Name: notas_internas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notas_internas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notas_internas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedidos_domicilio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos_domicilio (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    nombre_cliente text,
    telefono text,
    direccion text,
    detalle_pedido text,
    estado text
);


--
-- Name: pedidos_domicilio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedidos_domicilio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_domicilio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedidos_proveedores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos_proveedores (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    proveedor_id uuid,
    estado text,
    productos jsonb
);


--
-- Name: pedidos_proveedores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedidos_proveedores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_proveedores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personal_cuadrantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personal_cuadrantes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    empleado_id uuid,
    fecha date,
    turno text,
    hora_inicio text,
    hora_fin text,
    creado_en timestamp with time zone
);


--
-- Name: personal_empleados; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personal_empleados (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nombre text,
    pin_fichaje text,
    color_hex text,
    activo boolean,
    creado_en timestamp with time zone
);


--
-- Name: personal_fichajes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personal_fichajes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    empleado_id uuid,
    fecha date,
    hora_entrada timestamp with time zone,
    hora_salida timestamp with time zone,
    minutos_trabajados integer,
    editado_manualmente boolean,
    creado_en timestamp with time zone,
    hash_anterior text,
    hash_actual text
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sku text,
    nombre text,
    categoria text,
    precio_base numeric,
    igic_tipo numeric,
    stock_actual integer,
    precio_pvp numeric,
    codigo_barras text,
    stock_minimo integer,
    cantidad_reponer integer,
    familia text,
    fecha_caducidad date,
    marca text,
    subcategoria text,
    mascota text,
    caracteristicas text,
    edad text,
    tamano text,
    necesidad_especial text,
    sabor_principal text,
    gama text,
    composicion text
);


--
-- Name: productos_proveedores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_proveedores (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    producto_id uuid,
    proveedor_id uuid,
    precio_coste numeric
);


--
-- Name: proveedores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proveedores (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    nombre_empresa text,
    contacto text,
    cif text,
    telefono text,
    movil text,
    email text,
    direccion text,
    poblacion text,
    codigo_postal text,
    provincia text,
    pais text,
    codigo_pais text,
    idioma text,
    forma_pago text,
    iban text,
    swift text,
    persona_contacto text,
    notas text,
    frecuencia_reparto text,
    hora_limite text,
    dias_pago integer,
    pedido_minimo numeric
);


--
-- Name: proyectos_hitos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos_hitos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    proyecto_id bigint,
    titulo text,
    estado text,
    fecha_limite date,
    responsable text
);


--
-- Name: proyectos_hitos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos_hitos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_hitos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyectos_macro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos_macro (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    titulo text,
    descripcion text,
    estado text,
    fecha_inicio date,
    fecha_fin_estimada date,
    presupuesto_estimado numeric,
    coste_real numeric,
    notas text
);


--
-- Name: proyectos_macro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos_macro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_macro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicios_adiestramiento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servicios_adiestramiento (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    cliente text,
    mascota text,
    telefono text,
    motivo text,
    fecha_sesion text,
    estado text,
    observaciones text
);


--
-- Name: servicios_adiestramiento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.servicios_adiestramiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicios_adiestramiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicios_paseo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servicios_paseo (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    cliente text,
    mascota text,
    telefono text,
    tipo_paseo text,
    fecha text,
    estado text,
    observaciones text
);


--
-- Name: servicios_paseo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.servicios_paseo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicios_paseo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicios_recogida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servicios_recogida (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    cliente text,
    mascota text,
    telefono text,
    direccion text,
    fecha_recogida text,
    estado text,
    observaciones text
);


--
-- Name: servicios_recogida_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.servicios_recogida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicios_recogida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tareas_duenos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tareas_duenos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    titulo text,
    fecha_programada date,
    periodicidad text,
    estado text,
    notas text
);


--
-- Name: tareas_duenos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tareas_duenos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tareas_duenos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tareas_plannings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tareas_plannings (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    empleado_id uuid,
    rol_asignado text,
    tarea text,
    periodicidad text,
    fecha_puntual date,
    activo boolean,
    tipo text,
    tramo_horario text
);


--
-- Name: tareas_plannings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tareas_plannings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tareas_plannings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tareas_registro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tareas_registro (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    tarea_id bigint,
    empleado_id uuid,
    fecha_completada date,
    notas text
);


--
-- Name: tareas_registro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tareas_registro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tareas_registro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vales_tienda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vales_tienda (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    codigo_vale text,
    saldo_inicial numeric,
    saldo_actual numeric,
    estado text,
    id_ticket_origen integer,
    notas text
);


--
-- Name: vales_tienda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vales_tienda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vales_tienda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_historial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ventas_historial (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    fecha text,
    resumen text,
    total numeric,
    pago_efectivo numeric,
    pago_tarjeta numeric,
    pago_bizum numeric,
    pendiente numeric,
    cliente_deuda text,
    estado text,
    motivo_devolucion text,
    productos jsonb,
    pagado numeric,
    descuento_global numeric,
    metodo_pago text,
    hash_anterior text,
    hash_actual text,
    qr_verifactu text,
    estado_hacienda text,
    cliente_vip_nombre text,
    puntos_ganados integer,
    puntos_usados integer
);


--
-- Name: ventas_historial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ventas_historial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_historial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracion id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion ALTER COLUMN id SET DEFAULT nextval('public.configuracion_id_seq'::regclass);


--
-- Name: agenda_bloqueos agenda_bloqueos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_bloqueos
    ADD CONSTRAINT agenda_bloqueos_pkey PRIMARY KEY (id);


--
-- Name: citas citas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.citas
    ADD CONSTRAINT citas_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: compras compras_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT compras_pkey PRIMARY KEY (id);


--
-- Name: configuracion_negocio configuracion_negocio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_negocio
    ADD CONSTRAINT configuracion_negocio_pkey PRIMARY KEY (id);


--
-- Name: configuracion configuracion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion
    ADD CONSTRAINT configuracion_pkey PRIMARY KEY (id);


--
-- Name: control_caja control_caja_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.control_caja
    ADD CONSTRAINT control_caja_pkey PRIMARY KEY (id);


--
-- Name: cuentas_bancarias cuentas_bancarias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuentas_bancarias
    ADD CONSTRAINT cuentas_bancarias_pkey PRIMARY KEY (id);


--
-- Name: encargos_clientes encargos_clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encargos_clientes
    ADD CONSTRAINT encargos_clientes_pkey PRIMARY KEY (id);


--
-- Name: eventos_asistentes eventos_asistentes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_asistentes
    ADD CONSTRAINT eventos_asistentes_pkey PRIMARY KEY (id);


--
-- Name: eventos_ferias eventos_ferias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_ferias
    ADD CONSTRAINT eventos_ferias_pkey PRIMARY KEY (id);


--
-- Name: eventos_ferias_tareas eventos_ferias_tareas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_ferias_tareas
    ADD CONSTRAINT eventos_ferias_tareas_pkey PRIMARY KEY (id);


--
-- Name: eventos_talleres eventos_talleres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_talleres
    ADD CONSTRAINT eventos_talleres_pkey PRIMARY KEY (id);


--
-- Name: facturas facturas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_pkey PRIMARY KEY (id);


--
-- Name: gastos_recurrentes gastos_recurrentes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gastos_recurrentes
    ADD CONSTRAINT gastos_recurrentes_pkey PRIMARY KEY (id);


--
-- Name: marketing_objetivos marketing_objetivos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketing_objetivos
    ADD CONSTRAINT marketing_objetivos_pkey PRIMARY KEY (id);


--
-- Name: marketing_plan marketing_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketing_plan
    ADD CONSTRAINT marketing_plan_pkey PRIMARY KEY (id);


--
-- Name: mascotas mascotas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mascotas
    ADD CONSTRAINT mascotas_pkey PRIMARY KEY (id);


--
-- Name: movimientos_caja movimientos_caja_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimientos_caja
    ADD CONSTRAINT movimientos_caja_pkey PRIMARY KEY (id);


--
-- Name: notas_internas notas_internas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notas_internas
    ADD CONSTRAINT notas_internas_pkey PRIMARY KEY (id);


--
-- Name: pedidos_domicilio pedidos_domicilio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos_domicilio
    ADD CONSTRAINT pedidos_domicilio_pkey PRIMARY KEY (id);


--
-- Name: pedidos_proveedores pedidos_proveedores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos_proveedores
    ADD CONSTRAINT pedidos_proveedores_pkey PRIMARY KEY (id);


--
-- Name: personal_cuadrantes personal_cuadrantes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_cuadrantes
    ADD CONSTRAINT personal_cuadrantes_pkey PRIMARY KEY (id);


--
-- Name: personal_empleados personal_empleados_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_empleados
    ADD CONSTRAINT personal_empleados_pkey PRIMARY KEY (id);


--
-- Name: personal_fichajes personal_fichajes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_fichajes
    ADD CONSTRAINT personal_fichajes_pkey PRIMARY KEY (id);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: productos_proveedores productos_proveedores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_proveedores
    ADD CONSTRAINT productos_proveedores_pkey PRIMARY KEY (id);


--
-- Name: proveedores proveedores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT proveedores_pkey PRIMARY KEY (id);


--
-- Name: proyectos_hitos proyectos_hitos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_hitos
    ADD CONSTRAINT proyectos_hitos_pkey PRIMARY KEY (id);


--
-- Name: proyectos_macro proyectos_macro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos_macro
    ADD CONSTRAINT proyectos_macro_pkey PRIMARY KEY (id);


--
-- Name: servicios_adiestramiento servicios_adiestramiento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicios_adiestramiento
    ADD CONSTRAINT servicios_adiestramiento_pkey PRIMARY KEY (id);


--
-- Name: servicios_paseo servicios_paseo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicios_paseo
    ADD CONSTRAINT servicios_paseo_pkey PRIMARY KEY (id);


--
-- Name: servicios_recogida servicios_recogida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicios_recogida
    ADD CONSTRAINT servicios_recogida_pkey PRIMARY KEY (id);


--
-- Name: tareas_duenos tareas_duenos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tareas_duenos
    ADD CONSTRAINT tareas_duenos_pkey PRIMARY KEY (id);


--
-- Name: tareas_plannings tareas_plannings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tareas_plannings
    ADD CONSTRAINT tareas_plannings_pkey PRIMARY KEY (id);


--
-- Name: tareas_registro tareas_registro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tareas_registro
    ADD CONSTRAINT tareas_registro_pkey PRIMARY KEY (id);


--
-- Name: vales_tienda vales_tienda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vales_tienda
    ADD CONSTRAINT vales_tienda_pkey PRIMARY KEY (id);


--
-- Name: ventas_historial ventas_historial_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas_historial
    ADD CONSTRAINT ventas_historial_pkey PRIMARY KEY (id);


--
-- Name: eventos_asistentes eventos_asistentes_cliente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_asistentes
    ADD CONSTRAINT eventos_asistentes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE;


--
-- Name: eventos_asistentes eventos_asistentes_evento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos_asistentes
    ADD CONSTRAINT eventos_asistentes_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos_talleres(id) ON DELETE CASCADE;


--
-- Name: marketing_plan marketing_plan_objetivo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketing_plan
    ADD CONSTRAINT marketing_plan_objetivo_id_fkey FOREIGN KEY (objetivo_id) REFERENCES public.marketing_objetivos(id) ON DELETE SET NULL;


--
-- Mantenimiento de material (peluquería)
--

CREATE TABLE public.mantenimiento_materiales (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    nombre text NOT NULL,
    categoria text DEFAULT 'General',
    ubicacion text,
    activo boolean DEFAULT true,
    notas text
);

ALTER TABLE public.mantenimiento_materiales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mantenimiento_materiales_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.mantenimiento_planes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    material_id bigint NOT NULL,
    tipo_mantenimiento text NOT NULL,
    frecuencia_tipo text NOT NULL,
    dias_semana integer[] DEFAULT '{}',
    fecha_inicio date NOT NULL DEFAULT CURRENT_DATE,
    ultima_ejecucion date,
    proxima_ejecucion date,
    activo boolean DEFAULT true,
    rol_asignado text DEFAULT 'Rol: Peluquería',
    empleado_id uuid,
    notas text
);

ALTER TABLE public.mantenimiento_planes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mantenimiento_planes_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.mantenimiento_ejecuciones (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    plan_id bigint NOT NULL,
    fecha_programada date NOT NULL,
    fecha_realizada date,
    estado text NOT NULL DEFAULT 'Pendiente',
    notas text,
    empleado_id uuid,
    detalle_tecnico text
);

ALTER TABLE public.mantenimiento_ejecuciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mantenimiento_ejecuciones_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.mantenimiento_movimientos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    material_id bigint NOT NULL,
    tipo_movimiento text NOT NULL,
    fecha date NOT NULL DEFAULT CURRENT_DATE,
    detalle text,
    estado text DEFAULT 'Abierto',
    empleado_id uuid
);

ALTER TABLE public.mantenimiento_movimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mantenimiento_movimientos_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.mantenimiento_materiales
    ADD CONSTRAINT mantenimiento_materiales_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.mantenimiento_planes
    ADD CONSTRAINT mantenimiento_planes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.mantenimiento_ejecuciones
    ADD CONSTRAINT mantenimiento_ejecuciones_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.mantenimiento_movimientos
    ADD CONSTRAINT mantenimiento_movimientos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mantenimiento_planes
    ADD CONSTRAINT mantenimiento_planes_material_id_fkey
    FOREIGN KEY (material_id) REFERENCES public.mantenimiento_materiales(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.mantenimiento_ejecuciones
    ADD CONSTRAINT mantenimiento_ejecuciones_plan_id_fkey
    FOREIGN KEY (plan_id) REFERENCES public.mantenimiento_planes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.mantenimiento_movimientos
    ADD CONSTRAINT mantenimiento_movimientos_material_id_fkey
    FOREIGN KEY (material_id) REFERENCES public.mantenimiento_materiales(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX uq_mant_ejec_plan_fecha ON public.mantenimiento_ejecuciones(plan_id, fecha_programada);


--
-- PostgreSQL database dump complete
--
