-- Mantenimiento de material (peluquería / tienda)
-- Local primero; el mismo script se podrá aplicar en Supabase más adelante.

CREATE TABLE IF NOT EXISTS public.mantenimiento_materiales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    nombre text NOT NULL,
    categoria text DEFAULT 'General',
    ubicacion text,
    activo boolean DEFAULT true,
    notas text
);

CREATE TABLE IF NOT EXISTS public.mantenimiento_planes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    material_id bigint NOT NULL REFERENCES public.mantenimiento_materiales(id) ON DELETE CASCADE,
    tipo_mantenimiento text NOT NULL,
    frecuencia_tipo text NOT NULL,
    dias_semana integer[] DEFAULT '{}',
    fecha_inicio date NOT NULL DEFAULT CURRENT_DATE,
    ultima_ejecucion date,
    proxima_ejecucion date,
    activo boolean DEFAULT true,
    rol_asignado text DEFAULT 'Rol: Peluquería',
    empleado_id uuid,
    notas text
);

CREATE TABLE IF NOT EXISTS public.mantenimiento_ejecuciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    plan_id bigint NOT NULL REFERENCES public.mantenimiento_planes(id) ON DELETE CASCADE,
    fecha_programada date NOT NULL,
    fecha_realizada date,
    estado text NOT NULL DEFAULT 'Pendiente',
    notas text,
    empleado_id uuid,
    detalle_tecnico text
);

CREATE TABLE IF NOT EXISTS public.mantenimiento_movimientos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    material_id bigint NOT NULL REFERENCES public.mantenimiento_materiales(id) ON DELETE CASCADE,
    tipo_movimiento text NOT NULL,
    fecha date NOT NULL DEFAULT CURRENT_DATE,
    detalle text,
    estado text DEFAULT 'Abierto',
    empleado_id uuid
);

CREATE INDEX IF NOT EXISTS idx_mant_planes_material ON public.mantenimiento_planes(material_id);
CREATE INDEX IF NOT EXISTS idx_mant_planes_proxima ON public.mantenimiento_planes(proxima_ejecucion);
CREATE INDEX IF NOT EXISTS idx_mant_ejec_plan_fecha ON public.mantenimiento_ejecuciones(plan_id, fecha_programada);
CREATE INDEX IF NOT EXISTS idx_mant_ejec_estado ON public.mantenimiento_ejecuciones(estado);
CREATE INDEX IF NOT EXISTS idx_mant_mov_material ON public.mantenimiento_movimientos(material_id);

-- Unique: una ejecución pendiente/hecha por plan y fecha programada
CREATE UNIQUE INDEX IF NOT EXISTS uq_mant_ejec_plan_fecha
    ON public.mantenimiento_ejecuciones(plan_id, fecha_programada);
